### ISSUE TITLE
Can't send any chat messages

### ISSUE THREAD

**Issue by BobVul** [oliversalzburg/se-chat-reply-highlight#11]
Attempting to send with "enter" just clears the textbox and inserts a blank line. Attempting to send by clicking the "send" button just clears the textbox. Tested in Firefox.

No local changes since it last worked.

Console error: `TypeError: e.browser is undefined` on `se-chat-replyhelper.user.js:25:63`

**Comment by BobVul** [comment]
Looks like it's coming from the jQuery Caret plugin, most likely because [it depends on a deprecated/removed property](https://stackoverflow.com/questions/14524289/browser-is-undefined-error).

Either SE Chat updated their jQuery version (now `1.12.4`) or dropped their copy of jQuery Migrate. I think I remember seeing `JQMIGRATE` warnings before, so probably the latter.

Can be fixed by including jQuery Migrate in the userscript.

If SE at some point upgrades jQuery to 3.x, Migrate will no longer work and either Caret will have to be dropped or the userscript will have to include its own copy of jQuery.

**Comment by oliversalzburg** [comment]
Updated the user scripts in `dist`. Plugins no longer build, at least not on this machien.
