### ISSUE TITLE
Tooltip is sometimes distorted

### ISSUE THREAD

**Issue by terdon** [oliversalzburg/se-chat-reply-highlight#6]
I saw the following problem when hovering over the arrow that indicates when a message is a reply to a previous one:

![a](https://cloud.githubusercontent.com/assets/2124316/4707854/90eedd82-5891-11e4-8ab6-3bb0bbc82462.png)

I am guessing this is related to both users having very long names but I may well be wrong. The tooltip is displayed correctly if I move my mouse a little bit. This was observed using firefox 32.0.3 running on a  64 bit Debian.

**Comment by Cerberus-tm** [comment]
It seems this issue has been fixed! Sometimes I see truncated user names (which, to me, isn't really an issue), even for very short user names; but the distorted view is absent! Here is a link to @terdon 's original example for the record.
https://chat.stackexchange.com/transcript/95?m=18240092#18240092

**Comment by oliversalzburg** [comment]
Nice :D
